# Generated by Django 4.1.7 on 2023-04-26 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='company_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20, null=True)),
                ('c_email', models.EmailField(max_length=30, null=True)),
                ('c_number', models.IntegerField(null=True)),
                ('c_location', models.CharField(max_length=110, null=True)),
                ('c_licence', models.IntegerField(null=True)),
                ('c_industry', models.CharField(max_length=125, null=True)),
                ('c_year', models.IntegerField(null=True)),
                ('c_password', models.CharField(max_length=8, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, null=True)),
                ('lastname', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('number', models.IntegerField(null=True)),
                ('username', models.CharField(max_length=10, null=True)),
                ('password', models.CharField(max_length=8, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_firstname', models.CharField(max_length=20, null=True)),
                ('u_lastname', models.CharField(max_length=20, null=True)),
                ('u_email', models.EmailField(max_length=30, null=True)),
                ('u_number', models.IntegerField(null=True)),
                ('u_username', models.CharField(max_length=10, null=True)),
                ('u_password', models.CharField(max_length=8, null=True)),
                ('u_image', models.ImageField(null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_details', models.CharField(max_length=50, null=True)),
                ('job_description', models.TextField(max_length=500, null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('skills', models.CharField(max_length=100, null=True)),
                ('experience', models.CharField(max_length=40, null=True)),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('benifits', models.CharField(max_length=100, null=True)),
                ('pay_types', models.CharField(max_length=100, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company_reg')),
            ],
        ),
        migrations.CreateModel(
            name='applicant_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('num', models.IntegerField(null=True)),
                ('relocate', models.CharField(max_length=20, null=True)),
                ('resume', models.FileField(null=True, upload_to='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reg')),
            ],
        ),
    ]
